---
# file: traffic-ops-dev.yml

- hosts: traffic-ops-dev
  sudo: yes
  tasks:

    - name: Create RPM cache directory
      file: name='/vagrant/.cache' state=directory

    - name: Change Yum Cache directory
      ini_file: dest=/etc/yum.conf section=main option=cachedir value='/vagrant/.cache'

    - name: Enable Yum to keep files after installation
      ini_file: dest=/etc/yum.conf section=main option=keepcache value=1

    - name: Create file with root user
      ini_file: dest=~/.my.cnf section=client option=user value=root

    #- ini_file: dest=~/.my.cnf section=client option=password value=""

    - name: Installation of base packages
      yum: name={{ item }} state=present
      with_items:
        - epel-release
        - rpm-build
        - openssl-devel
        - git
        - hg
        - mysql-devel
        - mysql-server
        - libpcap-devel
        - libcurl-devel
        - libselinux-python
        - MySQL-python
        - perl-CPAN
        - perl-YAML
        - perl-devel
        - gcc

    - name: Install of Extra packages
      yum: name={{ item }} state=present
      with_items:
       - golang
    
    - name: Start MySql
      service: name=mysqld enabled=yes state=started

    - mysql_user: name=to_user password=twelve priv=to_development.*:ALL,GRANT state=present
    - mysql_user: name=to_user password=twelve priv=to_test.*:ALL,GRANT state=present
    - mysql_user: name=to_user password=twelve priv=to_integration.*:ALL,GRANT state=present

    - name: Create some directories for GO
      file: name={{ item }} state=directory owner=vagrant group=vagrant
      with_items:
        - /home/vagrant/go

    - name: Configure GOPATH
      lineinfile:
        dest: "/home/vagrant/.bashrc"
        line: "export GOPATH=/home/vagrant/go"

    - name: Test for cpanm
      shell: perl -MApp::cpanminus -e1
      register: result
      ignore_errors: true

    - name:  Install CPANm
      shell: curl -L http://cpanmin.us | perl - App::cpanminus
      when:  result|failed

    - name: Add /usr/local/bin to PATH
      lineinfile:
        dest: "/etc/profile.d/cpanm.sh"
        line: "pathmunge /usr/local/bin"
        create: yes

    - name: Ensure required Perl modules installed
      yum: name={{ item }} state=present
      with_items:
        - perl-Test-Harness
        - perl-Time-HiRes

    - name: Install Carton
      cpanm: name=MIYAGAWA/Carton-v1.0.15.tar.gz
      environment:
        PATH: "{{ansible_env.PATH}}:/usr/local/bin"

#        export GOPATH=/home/vagrant/go
#        mkdir -p $GOPATH
#        echo "export GOPATH=$GOPATH" >> /home/vagrant/.bash_profile
#        export PERL_MM_USE_DEFAULT=1
#        export PERL_MM_NONINTERACTIVE=1
#        export AUTOMATED_TESTING=1
#        /usr/bin/cpan -if YAML
#        /usr/bin/cpan -if CPAN
#        /usr/bin/cpan -if MIYAGAWA/Carton-v1.0.15.tar.gz
